exclude: ".*/migrations/.*"
repos:
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.16
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-django
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(js|jsx)$
        args:
          - "--max-warnings=0"
        additional_dependencies:
          - "eslint@6.x"
          - "eslint-config-react-app"
          - "@typescript-eslint/eslint-plugin@2.x"
          - "@typescript-eslint/parser@2.x"
          - "babel-eslint@10.x"
          - "eslint-plugin-flowtype@3.x"
          - "eslint-plugin-import@2.x"
          - "eslint-plugin-jsx-a11y@6.x"
          - "eslint-plugin-react@7.x"
          - "eslint-plugin-react-hooks@1.x"
