---
version: "3.7"

services:
  db:
    ports:
      - 5432:5432

  django:
    build: .
    volumes:
      - "./music_database:/code/music_database"
    ports:
      - 8000:8000

  parcel:
    image: "node:13"
    user: "${UID}"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - 34589:34589
    command: "npm run dev"
