---
version: "3.7"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: Chinook
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  django:
    image: music_database:${VERSION:-latest}
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://music_user:music_password@db/Chinook

volumes:
  pgdata:
